//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAssistedTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double UpperLimitTime {
            get {
                return ((double)(this["UpperLimitTime"]));
            }
            set {
                this["UpperLimitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double FinalReservedTime {
            get {
                return ((double)(this["FinalReservedTime"]));
            }
            set {
                this["FinalReservedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ChangeSlideTime {
            get {
                return ((double)(this["ChangeSlideTime"]));
            }
            set {
                this["ChangeSlideTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoLoadAfterBrowse {
            get {
                return ((bool)(this["IsAutoLoadAfterBrowse"]));
            }
            set {
                this["IsAutoLoadAfterBrowse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoShowDifferAfterLoad {
            get {
                return ((bool)(this["IsAutoShowDifferAfterLoad"]));
            }
            set {
                this["IsAutoShowDifferAfterLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OnlyText")]
        public string DifferenceType {
            get {
                return ((string)(this["DifferenceType"]));
            }
            set {
                this["DifferenceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-:-讲稿")]
        public string WordToPptRules {
            get {
                return ((string)(this["WordToPptRules"]));
            }
            set {
                this["WordToPptRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLocalData {
            get {
                return ((bool)(this["UseLocalData"]));
            }
            set {
                this["UseLocalData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ChatWaitTimeSeconds {
            get {
                return ((int)(this["ChatWaitTimeSeconds"]));
            }
            set {
                this["ChatWaitTimeSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaximumQuantity {
            get {
                return ((int)(this["MaximumQuantity"]));
            }
            set {
                this["MaximumQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GptWebName {
            get {
                return ((string)(this["GptWebName"]));
            }
            set {
                this["GptWebName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GptApiName {
            get {
                return ((string)(this["GptApiName"]));
            }
            set {
                this["GptApiName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GptApiIsRemoveEmptyLine {
            get {
                return ((bool)(this["GptApiIsRemoveEmptyLine"]));
            }
            set {
                this["GptApiIsRemoveEmptyLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int GptWebScale {
            get {
                return ((int)(this["GptWebScale"]));
            }
            set {
                this["GptWebScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int GptApiTimeoutSecond {
            get {
                return ((int)(this["GptApiTimeoutSecond"]));
            }
            set {
                this["GptApiTimeoutSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int TransWebScale {
            get {
                return ((int)(this["TransWebScale"]));
            }
            set {
                this["TransWebScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransWebName {
            get {
                return ((string)(this["TransWebName"]));
            }
            set {
                this["TransWebName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransApiName {
            get {
                return ((string)(this["TransApiName"]));
            }
            set {
                this["TransApiName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransApiAutoUpdate {
            get {
                return ((bool)(this["TransApiAutoUpdate"]));
            }
            set {
                this["TransApiAutoUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TransApiTimeoutSecond {
            get {
                return ((int)(this["TransApiTimeoutSecond"]));
            }
            set {
                this["TransApiTimeoutSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("自由输入")]
        public string GptApiTemplateName {
            get {
                return ((string)(this["GptApiTemplateName"]));
            }
            set {
                this["GptApiTemplateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GptApiStreamingMode {
            get {
                return ((bool)(this["GptApiStreamingMode"]));
            }
            set {
                this["GptApiStreamingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int GptApiHistoryNum {
            get {
                return ((int)(this["GptApiHistoryNum"]));
            }
            set {
                this["GptApiHistoryNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransApiIsAutoTranslate {
            get {
                return ((bool)(this["TransApiIsAutoTranslate"]));
            }
            set {
                this["TransApiIsAutoTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public string TransApiSourceLan {
            get {
                return ((string)(this["TransApiSourceLan"]));
            }
            set {
                this["TransApiSourceLan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chinese")]
        public string TransApiTargetLan {
            get {
                return ((string)(this["TransApiTargetLan"]));
            }
            set {
                this["TransApiTargetLan"] = value;
            }
        }
    }
}
